server:
  port: 8002


spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wzg_db01?useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: root
    password: 123
    druid:
      test-while-idle: true
      validation-query: SELECT 1


eureka:
  instance:
    instance-id: payment8002
    prefer-ip-address: true
    # Eureka客户端像服务端发送心跳的时间间隔，单位s，默认30s
#    lease-renewal-interval-in-seconds: 1
    # Rureka服务端在收到最后一次心跳后等待时间上线，单位为s，默认90s，超时将剔除服务
#    lease-expiration-duration-in-seconds: 2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: # 提供者注册到多个eureka中
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wzg.springcloud.entities       #所有Entity别名类所在包




