server:
  port: 80

eureka:
  instance:
    instance-id: consumer80
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/


spring:
  application:
    name: order-service
  zipkin:
    base-url: http://localhost:9411  # zipkin 地址
  sleuth:
    sampler:
      probability: 1 # 采样率值 介于0-1之间 ，1表示全部采集
  devtools:
    livereload:
      port: 3571

#  在使用 SpringBoot 热部署插件 devtools ,同时启动多个Application 时，控制台会报这个警告；
#  问题在于：DevToolsProperties 中配置了一个端口,默认是35729

